# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JoelsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JoelsTest
  pod "Alamofire", "~> 4.7"

  target 'JoelsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JoelsTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
